services:
  site:
    build: ./site
    ports:
      - "2900:80"
    restart: unless-stopped
    networks: 
      - net
  blog:
    build: 
      context: ./blog
      args:
        HOST: debbech.com
    restart: unless-stopped
    networks: 
      - net
    volumes:
      - "./blog/content:/app/content"

networks:
  net:
    driver: bridge